baseurl: /tech-and-data-standards

theme: jekyll-theme-time-machine

# Collections are groups of pages
collections:
  standards:
    output: true
    permalink: /standards/:path/
  meetings:
    output: true
    permalink: /meetings/:path/
